### ISSUE TITLE
如何同时使用多个游戏的DLC？How to use DLC for multiple games at the same time?

### ISSUE THREAD

**Issue by 7777777lai** [BlueAmulet/GreenLuma-2023-Manager#26]
您好，请问可以同时使用MHR和MHW的DLC吗，我使用的时候，它们会互相覆盖，只能同时使用一个游戏的DLC。

Hello, can I use the DLC of Monster Hunter: RISE and Monster Hunter: World at the same time, when I use them, they will cover each other, and only the DLC of one game can be used at the same time.

**Comment by BlueAmulet** [comment]
Monster Hunter: RISE and Monster Hunter: World both alone have absurd amounts of DLC that likely break GreenLuma's appid limit. This is a limit of GreenLuma itself and it is not possible at this moment to have all DLC from both games enabled at the same time.
