### ISSUE TITLE
Failed to update DllInjector.ini,check errors.log

### ISSUE THREAD

**Issue by ULLRZAIN** [BlueAmulet/GreenLuma-2023-Manager#28]
what is the problem？
Invalid file？
GreenLuma 2020 files download link is what？Or how to generate?

**Comment by ULLRZAIN** [comment]
Make sure the file is lost, where is the file download address?

**Comment by AcidClown** [comment]
Mine doesn't even come with dllinjector

**Comment by BlueAmulet** [comment]
The manager does not come with GreenLuma 2020 itself, DLLInjector.ini is a part of GreenLuma. I need the errors.log file to actually be able to help at all.
