### ISSUE TITLE
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato: 'D:\\GreenLuma.2020.Manager\\DLLInjector.ini'

### ISSUE THREAD

**Issue by Favatonante** [BlueAmulet/GreenLuma-2023-Manager#39]
ERROR:root:[WinError 2] Impossibile trovare il file specificato: 'D:\\GreenLuma.2020.Manager\\DLLInjector.ini' -> 'D:\\GreenLuma.2020.Manager\\DLLInjector.ini.bak'
Traceback (most recent call last):
  File "Qt\logic.py", line 225, in run_GreenLuma
  File "Qt\logic.py", line 404, in replaceConfig
  File "fileinput.py", line 252, in __next__
  File "fileinput.py", line 339, in _readline
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato: 'D:\\GreenLuma.2020.Manager\\DLLInjector.ini' -> 'D:\\GreenLuma.2020.Manager\\DLLInjector.ini.bak'

Path di steam e greenluma configurati correttamente, nella cartella scaricata non e' presente il DLLInjector.ini, a quanto ho capito e' integrato ma non lo trova comunque. Possibile fix ?

**Comment by BlueAmulet** [comment]
Please download GreenLuma from https://cs.rin.ru/forum/viewtopic.php?f=29&t=103709 , all you need are the files inside "NormalMode" folder. The path of GreenLuma in the manager should be configured to these files.
