### ISSUE TITLE
DLL Injector

### ISSUE THREAD

**Issue by BadBoyDragon** [BlueAmulet/GreenLuma-2023-Manager#46]
Every time I launch it and try and set my steam or GreenLuma path and/or click (Run GreenLuma) it says "Failed to update DLLInjector.ini, Cheak errors.log, and i did. I still dont know what to do. The DLL file isn't even in the folder itself.

**Comment by BlueAmulet** [comment]
Send your errors.log file then

**Comment by BlueAmulet** [comment]
It is likely that an antivirus deleted files related to GreenLuma, additional checks and messages have been added to the manager to provide better information for this situation. Please try to reinstall GreenLuma.
