### ISSUE TITLE
Failed to update DLLInjector.ini

### ISSUE THREAD

**Issue by cosmorixn** [BlueAmulet/GreenLuma-2023-Manager#47]
I don't know what im doing wrong, I put my steam path and green luma but after I press 'Run greenluma' this is all it says 
![image](https://user-images.githubusercontent.com/127044311/222975134-9f1e7241-4148-4904-bb64-e11e544a6226.png)
when I opened the file there was no DLLinjector file so im just kinda lost now
[errors.log](https://github.com/BlueAmulet/GreenLuma-2023-Manager/files/10892381/errors.log)

**Comment by BlueAmulet** [comment]
Something seems to have deleted your DLLInjector.ini file, just extract it from GreenLuma again.

**Comment by cosmorixn** [comment]
figured it out but now it's saying 'failed to inject dll' 
![image](https://user-images.githubusercontent.com/127044311/222983659-677fea82-1cff-4e83-a664-e9db1e5b0004.png)
[errors.log](https://github.com/BlueAmulet/GreenLuma-2023-Manager/files/10892851/errors.log)

**Comment by BlueAmulet** [comment]
You are also missing GreenLuma_2020_x86.dll now, I'm currently working on an update that will provide better checks and information for this kind of issue.
