### ISSUE TITLE
DLLInjector.exe is missing, please reinstall GreenLuma

### ISSUE THREAD

**Issue by nicknewbie2k3** [BlueAmulet/GreenLuma-2023-Manager#54]
![image](https://github.com/BlueAmulet/GreenLuma-2023-Manager/assets/116050319/0927d642-0731-4274-87fd-a5554e708c6a)
I cant really use it as it says it lacks file, I dont see it in your files... can you help me with it.

**Comment by BlueAmulet** [comment]
DLLInjector.exe is not provided by the manager, it is a part of the separate GreenLuma download that the manager informed you had to download on first launch.
If you did download it, check to make sure your antivirus did not delete it.
