### ISSUE TITLE
Hey man, idk if you are dead.

### ISSUE THREAD

**Issue by 343intact** [BlueAmulet/GreenLuma-2023-Manager#59]
Idk if you are alive, but I wanted to ask if I can add myself a prime dlc in cs:go this way? Also, is an app still usable? Last update was on Mar 6 2023, many things could've changed

**Comment by BlueAmulet** [comment]
This manager still works and hasn't needed major changes, been busy working on other projects. I don't play cs:go so I don't know anything about its dlcs

**Comment by BlueAmulet** [comment]
I am not an admin for rin.
