### ISSUE TITLE
dllinjector issues

### ISSUE THREAD

**Issue by xxgxxaxx** [BlueAmulet/GreenLuma-2023-Manager#60]
whenever I try to run greenluma I get the error "DLLInjecto.exe is missing please reinstall greenluma" and I have no idea what that means.

I am no techno wizard and have no idea how to fix this can anyone help?

**Comment by BlueAmulet** [comment]
DLLInjector.exe is a part of GreenLuma, the separate download you were supposed to get alongside the manager. It is commonly deleted by Windows Defender or other Antivirus, so make sure to whitelist it if it is being removed.

**Comment by xxgxxaxx** [comment]
> DLLInjector.exe is a part of GreenLuma, the separate download you were supposed to get alongside the manager. It is commonly deleted by Windows Defender or other Antivirus, so make sure to whitelist it if it is being removed.

it is something I download that is separate from the greenluma file I already have is that what I am understanding?

**Comment by BlueAmulet** [comment]
This project you're on right now, is my Manager. It is a tool to help manage lists of games and dlcs to unlock with GreenLuma.
GreenLuma is not included with this Manager, it is something that you have to separately download. Extract GreenLuma again to wherever you placed it last time, making sure that DLLInjector.exe, included with the GreenLuma download, does not get deleted by an antivirus.
