### ISSUE TITLE
Is this newer ?

### ISSUE THREAD

**Issue by DogancanYr** [BlueAmulet/GreenLuma-2023-Manager#63]
https://cs.rin.ru/forum/viewtopic.php?f=29&t=103709&hilit=greenluma

**Comment by BlueAmulet** [comment]
That is GreenLuma, you are meant to download that along with this manager. This manager is just a ... manager, for GreenLuma, and doesn't have any Game and DLC unlocking capabilities. It's sole purpose is to manage the AppList folder for GreenLuma.
