### ISSUE TITLE
I got the error Failed to Start the Game (Missing Executable).

### ISSUE THREAD

**Issue by DogancanYr** [BlueAmulet/GreenLuma-2023-Manager#66]
.

**Comment by BlueAmulet** [comment]
I need way more information than this ... what gave that error, what steps did you take to get that error, what are you trying to do, and where is the error log

**Comment by DogancanYr** [comment]
I was using it as usual in version 1.4.6, then I noticed that it was updated to version 1.4.7 and I updated it and then started playing other games. Then I wanted to download a new game and I encountered this error.It happens with all the newly downloaded games. Can you try it too?

**Comment by BlueAmulet** [comment]
Steam downloads tend to fail while Steam is running with GreenLuma, restart Steam without GL to download it properly or manually source the files yourself. Either way, not a problem with the manager.

**Comment by BlueAmulet** [comment]
This still has nothing to do with the manager.
