### ISSUE TITLE
Doesnt detect greenluma_2023_x86.dll

### ISSUE THREAD

**Issue by kAuFish** [BlueAmulet/GreenLuma-2023-Manager#67]
I get the error: "GreenLuma_2020_x86.dll is missing, please reinstall GreenLuma" when I click Run GreenLuma. I've reinstalled GreenLuma 3 times in the case that possibly something got thrown out.

In the errors file I get
`WARNING:root:Failed to detect Dll from DLLInjector.ini, using default of GreenLuma_2020_x86.dll
ERROR:root:GreenLuma_2020_x86.dll not found at D:\Program Files\GreenLuma_2023_1.4.7-Steam006\NormalMode\GreenLuma_2020_x86.dll`

I see that the repo is titled GreenLuma-2023-Manager, but are the newer GreenLuma-2023 versions not supported? The 2020 versions are not the first download on rin anymore. Any ideas you can throw towards me to get my computer to click in the right direction are also welcome. Thanks!

Update: I made the wording more accurate

**Comment by kAuFish** [comment]
Hi, I'm back. Here's what was going on:

Windows Defender without alerting me, was basically nuking all the data in these files. They were in the folder but they had 0 or 1kb. A quick check with 7zip showed that something amuck was going on here. 

Paused windows defender, and made an exception rule to the folder once extracted. No more issues. Hopefully this will help someone else out there. Thanks for the GUI btw!

**Comment by BlueAmulet** [comment]
The .dll used is based on what .dll is listed inside of the DLLInjector.ini file, if it is wanting GreenLuma_2020_x86.dll then you need to update the DLLInjector.ini to point to the right .dll instead
