### ISSUE TITLE
After restarting Steam ...

### ISSUE THREAD

**Issue by DogancanYr** [BlueAmulet/GreenLuma-2023-Manager#71]
I need to run greenluma again after steam restarts.

Wouldn't it be better if the software is triggered on steam startup ?

**Comment by BlueAmulet** [comment]
I do not make GreenLuma, I make this manager.

**Comment by DogancanYr** [comment]
> I do not make GreenLuma, I make this manager.

I know this, I just wanted to say, can you add a task scheduler that will trigger this when the original steam is opened instead of running the DLLInjector.exe software every time.

**Comment by BlueAmulet** [comment]
No.
